
# May 2026 Production Data Analysis

## 1. Project Overview
Data cleaning, validation, and analysis of production records
for May 2026.

## 2. Data Source
Excel master dataset containing daily records for production
Lines 1–9.

## 3. Tools and Libraries
- Python
- Pandas
- NumPy
- Jupyter Notebook

## 4. Data Preparation
- Load the master dataset
- Validate column names and data types
- Check missing values and duplicate records
- Validate production calculations

## 5. Analysis
To be performed after data validation.

In [1]:

# 1. IMPORT REQUIRED LIBRARIES

import pandas as pd
import numpy as np

# Display configuration
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

print("Libraries imported successfully.")
print(f"Pandas version: {pd.__version__}")
print(f"NumPy version: {np.__version__}")

Libraries imported successfully.
Pandas version: 2.3.2
NumPy version: 2.2.6

In [2]:

# 2. LOAD MASTER DATASET


from pathlib import Path

file_path = Path(r"D:\May_Analysis\data\May_2026_Daily_Reports.xlsx")
sheet_name = "Master Dataset"

if not file_path.exists():
    raise FileNotFoundError(
        f"Excel file not found: {file_path.resolve()}"
    )

df = pd.read_excel(
    file_path,
    sheet_name=sheet_name
)

print("Dataset loaded successfully.")
print(f"Dataset shape: {df.shape[0]} rows × {df.shape[1]} columns")

Dataset loaded successfully.
Dataset shape: 270 rows × 9 columns

In [3]:

# 3. INITIAL DATA PREVIEW

display(df.head(10))

  Report Date  LINE    HMR    LCR    PCR  WASTAGE    % M/C   PROD      PKG
0  2026-05-01     1  16354  16528  16208      320  1.93611  178.0  16020.0
1  2026-05-01     2  17634  17201  17113       88  0.51160  189.0  17010.0
2  2026-05-01     3  17214  17103  16560      543  3.17488  182.0  16380.0
3  2026-05-01     4  18681  19188  18997      191  0.99541  208.0  18720.0
4  2026-05-01     5  18666  19053  18399      654  3.43253  202.0  18180.0
5  2026-05-01     6  17651  17989  17856      133  0.73934  198.0  17820.0
6  2026-05-01     7  20443  20055  19874      181  0.90252  220.0  19800.0
7  2026-05-01     8  16806  16424  15898      526  3.20263  174.0  15660.0
8  2026-05-01     9  19466  19622  19168      454  2.31373    NaN      NaN
9  2026-05-02     1  18449  18290  17925      365  1.99563  198.0  17820.0

In [4]:

# 4. COLUMN NAMES AND DATA TYPES

print("Column names:")
print(df.columns.tolist())

print("\nDataset information:")
df.info()

Column names:
['Report Date', 'LINE', 'HMR', 'LCR', 'PCR', 'WASTAGE', '% M/C', 'PROD', 'PKG']

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Report Date  270 non-null    datetime64[ns]
 1   LINE         270 non-null    int64
 2   HMR          270 non-null    int64
 3   LCR          270 non-null    int64
 4   PCR          270 non-null    int64
 5   WASTAGE      270 non-null    int64
 6   % M/C        270 non-null    float64
 7   PROD         240 non-null    float64
 8   PKG          240 non-null    float64
dtypes: datetime64[ns](1), float64(3), int64(5)
memory usage: 19.1 KB

In [5]:
# 5. DATA QUALITY VALIDATION

# 1. Validate dataset dimensions
print("=" * 60)
print("DATA QUALITY VALIDATION REPORT")
print("=" * 60)

print(f"\nTotal records       : {len(df)}")
print(f"Total columns       : {len(df.columns)}")
print(f"Duplicate rows      : {df.duplicated().sum()}")

# 2. Validate column names
expected_columns = [
    "Report Date", "LINE", "HMR", "LCR", "PCR",
    "WASTAGE", "% M/C", "PROD", "PKG"
]

print("\nColumn structure:")
print("Expected columns match:", list(df.columns) == expected_columns)

# 3. Check missing values
missing_report = pd.DataFrame({
    "Missing Count": df.isna().sum(),
    "Missing Percentage": (df.isna().mean() * 100).round(2)
})

print("\nMissing Values Report:")
display(missing_report)

# 4. Check data types
print("\nData Types:")
display(df.dtypes.rename("Data Type").to_frame())

# 5. Check report date coverage
dates = pd.to_datetime(df["Report Date"], errors="coerce")

print("\nDate Validation:")
print("Invalid or missing dates:", dates.isna().sum())
print("Unique report dates:", dates.nunique())

if dates.notna().any():
    print("First report date:", dates.min().date())
    print("Last report date :", dates.max().date())

# 6. Check line coverage
print("\nLine Validation:")
print("Unique lines:", sorted(df["LINE"].dropna().unique().tolist()))
print("Missing line values:", df["LINE"].isna().sum())

print("\nValidation report completed.")

============================================================
DATA QUALITY VALIDATION REPORT
============================================================

Total records       : 270
Total columns       : 9
Duplicate rows      : 0

Column structure:
Expected columns match: True

Missing Values Report:

             Missing Count  Missing Percentage
Report Date              0                0.00
LINE                     0                0.00
HMR                      0                0.00
LCR                      0                0.00
PCR                      0                0.00
WASTAGE                  0                0.00
% M/C                    0                0.00
PROD                    30               11.11
PKG                     30               11.11

Data Types:

                  Data Type
Report Date  datetime64[ns]
LINE                  int64
HMR                   int64
LCR                   int64
PCR                   int64
WASTAGE               int64
% M/C               float64
PROD                float64
PKG                 float64

Date Validation:
Invalid or missing dates: 0
Unique report dates: 30
First report date: 2026-05-01
Last report date : 2026-05-30

Line Validation:
Unique lines: [1, 2, 3, 4, 5, 6, 7, 8, 9]
Missing line values: 0

Validation report completed.

In [6]:
# 7. VALIDATE MISSING PROD AND PKG RECORDS

missing_rows = df.loc[
    df["PROD"].isna() | df["PKG"].isna(),
    ["Report Date", "LINE", "PROD", "PKG"]
].copy()

print("Rows with missing PROD or PKG:", len(missing_rows))

print("\nLine-wise missing value summary:")
display(
    df.groupby("LINE")[["PROD", "PKG"]]
      .apply(lambda group: group.isna().sum())
      .rename(columns={
          "PROD": "Missing PROD",
          "PKG": "Missing PKG"
      })
)

print("\nMissing records preview:")
display(missing_rows.head(10))

Rows with missing PROD or PKG: 30

Line-wise missing value summary:

      Missing PROD  Missing PKG
LINE
1                0            0
2                0            0
3                0            0
4                0            0
5                0            0
6                0            0
7                0            0
8                0            0
9               30           30

Missing records preview:

   Report Date  LINE  PROD  PKG
8   2026-05-01     9   NaN  NaN
17  2026-05-02     9   NaN  NaN
26  2026-05-03     9   NaN  NaN
35  2026-05-04     9   NaN  NaN
44  2026-05-05     9   NaN  NaN
53  2026-05-06     9   NaN  NaN
62  2026-05-07     9   NaN  NaN
71  2026-05-08     9   NaN  NaN
80  2026-05-09     9   NaN  NaN
89  2026-05-10     9   NaN  NaN

In [7]:
# 8. PRODUCTION CALCULATION VALIDATION

# Calculate expected machine wastage
expected_wastage = df["LCR"] - df["PCR"]

# Identify records where the reported wastage differs
wastage_mismatch = df.loc[
    df["WASTAGE"] != expected_wastage,
    ["Report Date", "LINE", "LCR", "PCR", "WASTAGE"]
].copy()

print("Wastage calculation validation")
print("-" * 45)
print("Total records:", len(df))
print("Mismatched records:", len(wastage_mismatch))

if wastage_mismatch.empty:
    print("Status: PASSED — WASTAGE equals LCR - PCR.")
else:
    print("Status: REVIEW REQUIRED")
    display(wastage_mismatch.head(20))


# Calculate expected machine wastage
expected_wastage = df["LCR"] - df["PCR"]

# Identify records where the reported wastage differs
wastage_mismatch = df.loc[
    df["WASTAGE"] != expected_wastage,
    ["Report Date", "LINE", "LCR", "PCR", "WASTAGE"]
].copy()

print("Wastage calculation validation")
print("-" * 45)
print("Total records:", len(df))
print("Mismatched records:", len(wastage_mismatch))

if wastage_mismatch.empty:
    print("Status: PASSED — WASTAGE equals LCR - PCR.")
else:
    print("Status: REVIEW REQUIRED")
    display(wastage_mismatch.head(20))


# Calculate expected machine wastage
expected_wastage = df["LCR"] - df["PCR"]

# Identify records where the reported wastage differs
wastage_mismatch = df.loc[
    df["WASTAGE"] != expected_wastage,
    ["Report Date", "LINE", "LCR", "PCR", "WASTAGE"]
].copy()

print("Wastage calculation validation")
print("-" * 45)
print("Total records:", len(df))
print("Mismatched records:", len(wastage_mismatch))

if wastage_mismatch.empty:
    print("Status: PASSED — WASTAGE equals LCR - PCR.")
else:
    print("Status: REVIEW REQUIRED")
    display(wastage_mismatch.head(20))

Wastage calculation validation
---------------------------------------------
Total records: 270
Mismatched records: 0
Status: PASSED — WASTAGE equals LCR - PCR.
Wastage calculation validation
---------------------------------------------
Total records: 270
Mismatched records: 0
Status: PASSED — WASTAGE equals LCR - PCR.
Wastage calculation validation
---------------------------------------------
Total records: 270
Mismatched records: 0
Status: PASSED — WASTAGE equals LCR - PCR.

In [8]:
# 9. MACHINE WASTAGE PERCENTAGE VALIDATION

expected_percentage = (df["WASTAGE"] / df["LCR"]) * 100

# Allow a small tolerance for decimal rounding
percentage_mismatch = df.loc[
    ~np.isclose(
        df["% M/C"],
        expected_percentage,
        rtol=1e-05,
        atol=0.01,
        equal_nan=False
    ),
    ["Report Date", "LINE", "LCR", "WASTAGE", "% M/C"]
].copy()

print("Machine wastage percentage validation")
print("-" * 45)
print("Total records:", len(df))
print("Mismatched records:", len(percentage_mismatch))

if percentage_mismatch.empty:
    print("Status: PASSED")
else:
    print("Status: REVIEW REQUIRED")
    display(percentage_mismatch.head(20))

Machine wastage percentage validation
---------------------------------------------
Total records: 270
Mismatched records: 0
Status: PASSED

In [9]:
# 10. OPERATIONAL WASTAGE VALIDATION

valid_pkg = df["PKG"].notna()

operational_wastage = (
    df.loc[valid_pkg, "PCR"] -
    df.loc[valid_pkg, "PKG"]
)

# Check that operational wastage is non-negative
negative_operational_wastage = df.loc[
    valid_pkg & ((df["PCR"] - df["PKG"]) < 0),
    ["Report Date", "LINE", "PCR", "PKG"]
].copy()

print("Operational wastage validation")
print("-" * 45)
print("Records with PKG available:", valid_pkg.sum())
print("Records with PKG missing:", (~valid_pkg).sum())
print(
    "Negative operational wastage records:",
    len(negative_operational_wastage)
)

if negative_operational_wastage.empty:
    print("Status: PASSED — no negative operational wastage found.")
else:
    print("Status: REVIEW REQUIRED")
    display(negative_operational_wastage.head(20))

Operational wastage validation
---------------------------------------------
Records with PKG available: 240
Records with PKG missing: 30
Negative operational wastage records: 0
Status: PASSED — no negative operational wastage found.

In [10]:
# 11. FINAL DATA QUALITY SUMMARY

total_records = len(df)
total_columns = len(df.columns)
duplicate_rows = df.duplicated().sum()
missing_cells = df.isna().sum().sum()
invalid_dates = pd.to_datetime(
    df["Report Date"], errors="coerce"
).isna().sum()

summary = pd.DataFrame({
    "Validation Check": [
        "Total records",
        "Total columns",
        "Duplicate rows",
        "Missing cells",
        "Invalid report dates",
        "Unique report dates",
        "Unique production lines",
        "Wastage formula mismatches",
        "Machine wastage percentage mismatches",
        "Negative operational wastage records"
    ],
    "Result": [
        total_records,
        total_columns,
        duplicate_rows,
        missing_cells,
        invalid_dates,
        df["Report Date"].nunique(),
        df["LINE"].nunique(),
        len(wastage_mismatch),
        len(percentage_mismatch),
        len(negative_operational_wastage)
    ]
})

display(summary)

                        Validation Check  Result
0                          Total records     270
1                          Total columns       9
2                         Duplicate rows       0
3                          Missing cells      60
4                   Invalid report dates       0
5                    Unique report dates      30
6                Unique production lines       9
7             Wastage formula mismatches       0
8  Machine wastage percentage mismatches       0
9   Negative operational wastage records       0

In [11]:
# 12. EXPORT VALIDATED MASTER DATASET

from pathlib import Path

output_file = Path("May_2026_Validated_Master_Dataset.xlsx")

df.to_excel(
    output_file,
    sheet_name="Master Dataset",
    index=False
)

print("Export completed successfully.")
print("File:", output_file.resolve())
print("Rows exported:", len(df))
print("Columns exported:", len(df.columns))

Export completed successfully.
File: D:\May_Analysis\notebooks\May_2026_Validated_Master_Dataset.xlsx
Rows exported: 270
Columns exported: 9

In [12]:
# 13. VERIFY EXPORTED DATASET

from pathlib import Path
import pandas as pd

output_file = Path("May_2026_Validated_Master_Dataset.xlsx")

if output_file.exists():
    df_check = pd.read_excel(
        output_file,
        sheet_name="Master Dataset"
    )

    print("Export verification: PASSED")
    print("File size (KB):", round(output_file.stat().st_size / 1024, 2))
    print("Rows:", df_check.shape[0])
    print("Columns:", df_check.shape[1])
    print("Duplicate rows:", df_check.duplicated().sum())
    print("Missing cells:", df_check.isna().sum().sum())
else:
    print("Export verification: FAILED — file not found.")

Export verification: PASSED
File size (KB): 18.01
Rows: 270
Columns: 9
Duplicate rows: 0
Missing cells: 60

In [13]:
# 14. INITIALIZE PRODUCTION ANALYSIS

import pandas as pd
import numpy as np

file_path = "May_2026_Validated_Master_Dataset.xlsx"

production_df = pd.read_excel(
    file_path,
    sheet_name="Master Dataset"
)

# Ensure report dates use datetime format
production_df["Report Date"] = pd.to_datetime(
    production_df["Report Date"],
    errors="coerce"
)

print("Production analysis dataset loaded.")
print("-" * 45)
print("Records:", len(production_df))
print("Columns:", len(production_df.columns))
print("Date range:",
      production_df["Report Date"].min().date(),
      "to",
      production_df["Report Date"].max().date())
print("Production lines:",
      sorted(production_df["LINE"].dropna().unique().tolist()))

display(production_df.head())

Production analysis dataset loaded.
---------------------------------------------
Records: 270
Columns: 9
Date range: 2026-05-01 to 2026-05-30
Production lines: [1, 2, 3, 4, 5, 6, 7, 8, 9]

  Report Date  LINE    HMR    LCR    PCR  WASTAGE    % M/C   PROD      PKG
0  2026-05-01     1  16354  16528  16208      320  1.93611  178.0  16020.0
1  2026-05-01     2  17634  17201  17113       88  0.51160  189.0  17010.0
2  2026-05-01     3  17214  17103  16560      543  3.17488  182.0  16380.0
3  2026-05-01     4  18681  19188  18997      191  0.99541  208.0  18720.0
4  2026-05-01     5  18666  19053  18399      654  3.43253  202.0  18180.0

In [14]:
# 15. RECORD COUNT VALIDATION BY PRODUCTION LINE

line_validation = (
    production_df.groupby("LINE")
    .agg(
        Total_Records=("Report Date", "size"),
        Unique_Dates=("Report Date", "nunique")
    )
    .reset_index()
)

line_validation["Expected_Records"] = 30
line_validation["Validation_Status"] = np.where(
    (line_validation["Total_Records"] == 30) &
    (line_validation["Unique_Dates"] == 30),
    "PASS",
    "REVIEW"
)

display(line_validation)

print("\nOverall validation:")
print("Total records:", production_df.shape[0])
print("Lines checked:", production_df["LINE"].nunique())
print(
    "Lines passing validation:",
    (line_validation["Validation_Status"] == "PASS").sum()
)

   LINE  Total_Records  Unique_Dates  Expected_Records Validation_Status
0     1             30            30                30              PASS
1     2             30            30                30              PASS
2     3             30            30                30              PASS
3     4             30            30                30              PASS
4     5             30            30                30              PASS
5     6             30            30                30              PASS
6     7             30            30                30              PASS
7     8             30            30                30              PASS
8     9             30            30                30              PASS

Overall validation:
Total records: 270
Lines checked: 9
Lines passing validation: 9

In [15]:
# 16. DAILY PRODUCTION LINE VALIDATION

daily_line_check = (
    production_df.groupby("Report Date")
    .agg(
        Total_Records=("LINE", "size"),
        Unique_Lines=("LINE", "nunique")
    )
    .reset_index()
)

daily_line_check["Status"] = np.where(
    (daily_line_check["Total_Records"] == 9) &
    (daily_line_check["Unique_Lines"] == 9),
    "PASS",
    "REVIEW"
)

display(daily_line_check)

print("\nDaily validation summary")
print("-" * 35)
print("Dates checked:", len(daily_line_check))
print("Dates passed:", (daily_line_check["Status"] == "PASS").sum())
print("Dates requiring review:", (daily_line_check["Status"] == "REVIEW").sum())

   Report Date  Total_Records  Unique_Lines Status
0   2026-05-01              9             9   PASS
1   2026-05-02              9             9   PASS
2   2026-05-03              9             9   PASS
3   2026-05-04              9             9   PASS
4   2026-05-05              9             9   PASS
5   2026-05-06              9             9   PASS
6   2026-05-07              9             9   PASS
7   2026-05-08              9             9   PASS
8   2026-05-09              9             9   PASS
9   2026-05-10              9             9   PASS
10  2026-05-11              9             9   PASS
11  2026-05-12              9             9   PASS
12  2026-05-13              9             9   PASS
13  2026-05-14              9             9   PASS
14  2026-05-15              9             9   PASS
15  2026-05-16              9             9   PASS
16  2026-05-17              9             9   PASS
17  2026-05-18              9             9   PASS
18  2026-05-19              9             9   PASS
19  2026-05-20              9             9   PASS
20  2026-05-21              9             9   PASS
21  2026-05-22              9             9   PASS
22  2026-05-23              9             9   PASS
23  2026-05-24              9             9   PASS
24  2026-05-25              9             9   PASS
25  2026-05-26              9             9   PASS
26  2026-05-27              9             9   PASS
27  2026-05-28              9             9   PASS
28  2026-05-29              9             9   PASS
29  2026-05-30              9             9   PASS

Daily validation summary
-----------------------------------
Dates checked: 30
Dates passed: 30
Dates requiring review: 0

In [16]:
# 17. DUPLICATE DATE-LINE VALIDATION

duplicate_date_line = production_df[
    production_df.duplicated(
        subset=["Report Date", "LINE"],
        keep=False
    )
].sort_values(["Report Date", "LINE"])

print("Duplicate date-line combinations:",
      len(duplicate_date_line))

if duplicate_date_line.empty:
    print("Status: PASSED — each date-line combination is unique.")
else:
    print("Status: REVIEW REQUIRED")
    display(
        duplicate_date_line[
            ["Report Date", "LINE", "HMR", "LCR", "PCR"]
        ]
    )

Duplicate date-line combinations: 0
Status: PASSED — each date-line combination is unique.

In [17]:
# 18. PRODUCTION QUANTITY VALIDATION

quantity_columns = ["HMR", "LCR", "PCR", "WASTAGE", "PROD", "PKG"]

quantity_validation = []

for column in quantity_columns:
    values = pd.to_numeric(production_df[column], errors="coerce")

    quantity_validation.append({
        "Column": column,
        "Negative_Values": int((values < 0).sum()),
        "Missing_Values": int(values.isna().sum()),
        "Status": (
            "PASS"
            if not (values < 0).any()
            else "REVIEW"
        )
    })

quantity_report = pd.DataFrame(quantity_validation)

display(quantity_report)

    Column  Negative_Values  Missing_Values Status
0      HMR                0               0   PASS
1      LCR                0               0   PASS
2      PCR                0               0   PASS
3  WASTAGE                0               0   PASS
4     PROD                0              30   PASS
5      PKG                0              30   PASS

In [18]:
# 19. TOTAL WASTAGE VALIDATION

valid_rows = production_df["PKG"].notna()

expected_total_wastage = (
    production_df.loc[valid_rows, "WASTAGE"]
    + production_df.loc[valid_rows, "PCR"]
    - production_df.loc[valid_rows, "PKG"]
)

calculated_total_wastage = (
    production_df.loc[valid_rows, "LCR"]
    - production_df.loc[valid_rows, "PKG"]
)

total_wastage_mismatch = (
    expected_total_wastage != calculated_total_wastage
)

print("Total wastage validation")
print("-" * 40)
print("Records checked:", int(valid_rows.sum()))
print("Mismatches:", int(total_wastage_mismatch.sum()))

if not total_wastage_mismatch.any():
    print("Status: PASSED")
else:
    print("Status: REVIEW REQUIRED")

Total wastage validation
----------------------------------------
Records checked: 240
Mismatches: 0
Status: PASSED

In [19]:
# 21. CONSOLIDATED VALIDATION STATUS

validation_summary = pd.DataFrame([
    ["Dataset structure", "270 records, 9 columns", "PASS"],
    ["Date coverage", "30 report dates", "PASS"],
    ["Line coverage", "9 lines per date", "PASS"],
    ["Duplicate full rows", "0 duplicates", "PASS"],
    ["Duplicate date-line pairs", "0 duplicates", "PASS"],
    ["Invalid report dates", "0", "PASS"],
    ["Negative quantities", "0", "PASS"],
    ["Machine wastage formula", "LCR - PCR", "PASS"],
    ["Machine wastage percentage", "Formula verified", "PASS"],
    ["Operational wastage", "No negative values", "PASS"],
    ["Total wastage formula", "LCR - PKG", "PASS"],
    ["Packing vs production", "No PKG > PROD records", "PASS"],
    ["Line 9 PROD/PKG values", "Missing; source review required", "REVIEW"]
], columns=["Validation Check", "Result", "Status"])

display(validation_summary)

              Validation Check                           Result  Status
0            Dataset structure           270 records, 9 columns    PASS
1                Date coverage                  30 report dates    PASS
2                Line coverage                 9 lines per date    PASS
3          Duplicate full rows                     0 duplicates    PASS
4    Duplicate date-line pairs                     0 duplicates    PASS
5         Invalid report dates                                0    PASS
6          Negative quantities                                0    PASS
7      Machine wastage formula                        LCR - PCR    PASS
8   Machine wastage percentage                 Formula verified    PASS
9          Operational wastage               No negative values    PASS
10       Total wastage formula                        LCR - PKG    PASS
11       Packing vs production            No PKG > PROD records    PASS
12      Line 9 PROD/PKG values  Missing; source review required  REVIEW

In [20]:
# 22. DAILY PRODUCTION SUMMARY

daily_summary = (
    production_df.groupby("Report Date")
    .agg(
        Total_HMR=("HMR", "sum"),
        Total_LCR=("LCR", "sum"),
        Total_PCR=("PCR", "sum"),
        Total_Machine_Wastage=("WASTAGE", "sum"),
        Total_PROD=("PROD", "sum"),
        Total_PKG=("PKG", "sum"),
        Lines_Reported=("LINE", "nunique")
    )
    .reset_index()
)

# Calculate total wastage where the required values are available
daily_summary["Total_Wastage"] = (
    daily_summary["Total_LCR"] - daily_summary["Total_PKG"]
)

# Calculate machine wastage percentage
daily_summary["Machine_Wastage_Percentage"] = np.where(
    daily_summary["Total_LCR"] != 0,
    daily_summary["Total_Machine_Wastage"]
    / daily_summary["Total_LCR"] * 100,
    np.nan
)

display(daily_summary.head(10))

print("Daily summary created.")
print("Number of daily records:", len(daily_summary))

,Report Date,Total_HMR,Total_LCR,Total_PCR,Total_Machine_Wastage,Total_PROD,Total_PKG,Lines_Reported,Total_Wastage,Machine_Wastage_Percentage
0,2026-05-01,162915,163163,160073,3090,1551.0,139590.0,9,23573.0,1.893812
1,2026-05-02,163243,159078,155721,3357,1512.0,136080.0,9,22998.0,2.110286
2,2026-05-03,150027,145955,143103,2852,1398.0,125820.0,9,20135.0,1.954027
3,2026-05-04,166079,164087,160941,3146,1563.0,140670.0,9,23417.0,1.917276
4,2026-05-05,170530,166686,163817,2869,1601.0,144090.0,9,22596.0,1.721200
5,2026-05-06,164898,162484,158846,3638,1563.0,140670.0,9,21814.0,2.238990
6,2026-05-07,164200,160230,157297,2933,1541.0,138690.0,9,21540.0,1.830494
7,2026-05-08,166258,164979,161035,3944,1577.0,141930.0,9,23049.0,2.390607
8,2026-05-09,160285,155628,152511,3117,1498.0,134820.0,9,20808.0,2.002853
9,2026-05-10,168208,165575,162076,3499,1575.0,141750.0,9,23825.0,2.113242

Daily summary created.
Number of daily records: 30

In [21]:
# 23. MONTHLY PRODUCTION SUMMARY BY LINE

line_summary = (
    production_df.groupby("LINE")
    .agg(
        Days_Reported=("Report Date", "nunique"),
        Total_HMR=("HMR", "sum"),
        Total_LCR=("LCR", "sum"),
        Total_PCR=("PCR", "sum"),
        Total_Machine_Wastage=("WASTAGE", "sum"),
        Total_PROD=("PROD", "sum"),
        Total_PKG=("PKG", "sum")
    )
    .reset_index()
)

# Calculate machine wastage percentage
line_summary["Machine_Wastage_Percentage"] = np.where(
    line_summary["Total_LCR"] != 0,
    line_summary["Total_Machine_Wastage"]
    / line_summary["Total_LCR"] * 100,
    np.nan
)

# Identify completeness of production and packing data
line_summary["PROD_Missing_Days"] = (
    production_df.groupby("LINE")["PROD"]
    .apply(lambda s: s.isna().sum())
    .to_numpy()
)

line_summary["PKG_Missing_Days"] = (
    production_df.groupby("LINE")["PKG"]
    .apply(lambda s: s.isna().sum())
    .to_numpy()
)

display(line_summary.round(2))

print("\nMonthly line summary created.")
print("Lines included:", len(line_summary))

,LINE,Days_Reported,Total_HMR,Total_LCR,Total_PCR,Total_Machine_Wastage,Total_PROD,Total_PKG,Machine_Wastage_Percentage,PROD_Missing_Days,PKG_Missing_Days
0,1,30,536899,533156,522789,10367,5759.0,518310.0,1.94,0,0
1,2,30,544761,533207,521759,11448,5746.0,517140.0,2.15,0,0
2,3,30,540302,530786,520460,10326,5733.0,515970.0,1.95,0,0
3,4,30,549860,539655,529505,10150,5836.0,525240.0,1.88,0,0
4,5,30,554973,547020,534082,12938,5882.0,529380.0,2.37,0,0
5,6,30,534483,526801,517042,9759,5694.0,512460.0,1.85,0,0
6,7,30,553288,542971,532296,10675,5867.0,528030.0,1.97,0,0
7,8,30,532928,524937,514906,10031,5670.0,510300.0,1.91,0,0
8,9,30,553560,548943,536386,12557,0.0,0.0,2.29,30,30

Monthly line summary created.
Lines included: 9

In [22]:
# 24. CORRECT MISSING TOTALS IN LINE SUMMARY

for line in [9]:
    missing_prod = line_summary.loc[
        line_summary["LINE"] == line, "PROD_Missing_Days"
    ].iloc[0]

    missing_pkg = line_summary.loc[
        line_summary["LINE"] == line, "PKG_Missing_Days"
    ].iloc[0]

    if missing_prod > 0:
        line_summary.loc[
            line_summary["LINE"] == line, "Total_PROD"
        ] = np.nan

    if missing_pkg > 0:
        line_summary.loc[
            line_summary["LINE"] == line, "Total_PKG"
        ] = np.nan

display(
    line_summary[
        [
            "LINE",
            "Days_Reported",
            "Total_LCR",
            "Total_PCR",
            "Total_Machine_Wastage",
            "Total_PROD",
            "Total_PKG",
            "PROD_Missing_Days",
            "PKG_Missing_Days"
        ]
    ].round(2)
)

,LINE,Days_Reported,Total_LCR,Total_PCR,Total_Machine_Wastage,Total_PROD,Total_PKG,PROD_Missing_Days,PKG_Missing_Days
0,1,30,533156,522789,10367,5759.0,518310.0,0,0
1,2,30,533207,521759,11448,5746.0,517140.0,0,0
2,3,30,530786,520460,10326,5733.0,515970.0,0,0
3,4,30,539655,529505,10150,5836.0,525240.0,0,0
4,5,30,547020,534082,12938,5882.0,529380.0,0,0
5,6,30,526801,517042,9759,5694.0,512460.0,0,0
6,7,30,542971,532296,10675,5867.0,528030.0,0,0
7,8,30,524937,514906,10031,5670.0,510300.0,0,0
8,9,30,548943,536386,12557,NaN,NaN,30,30

In [23]:
# 25. LINE-WISE DATA COMPLETENESS REPORT


completeness_report = (
    production_df.groupby("LINE")
    .agg(
        Total_Records=("Report Date", "size"),
        PROD_Available=("PROD", "count"),
        PKG_Available=("PKG", "count")
    )
    .reset_index()
)

completeness_report["PROD_Completeness_%"] = (
    completeness_report["PROD_Available"]
    / completeness_report["Total_Records"] * 100
).round(2)

completeness_report["PKG_Completeness_%"] = (
    completeness_report["PKG_Available"]
    / completeness_report["Total_Records"] * 100
).round(2)

display(completeness_report)

print("\nData completeness report created.")

   LINE  Total_Records  PROD_Available  PKG_Available  PROD_Completeness_%  PKG_Completeness_%
0     1             30              30             30                100.0               100.0
1     2             30              30             30                100.0               100.0
2     3             30              30             30                100.0               100.0
3     4             30              30             30                100.0               100.0
4     5             30              30             30                100.0               100.0
5     6             30              30             30                100.0               100.0
6     7             30              30             30                100.0               100.0
7     8             30              30             30                100.0               100.0
8     9             30               0              0                  0.0                 0.0

Data completeness report created.

In [24]:
# 26. DAILY DATA COMPLETENESS STATUS

daily_completeness = (
    production_df.groupby("Report Date")
    .agg(
        Total_Lines=("LINE", "nunique"),
        PROD_Missing=("PROD", lambda s: s.isna().sum()),
        PKG_Missing=("PKG", lambda s: s.isna().sum())
    )
    .reset_index()
)

daily_completeness["PROD_Status"] = np.where(
    daily_completeness["PROD_Missing"] == 0,
    "Complete",
    "Incomplete"
)

daily_completeness["PKG_Status"] = np.where(
    daily_completeness["PKG_Missing"] == 0,
    "Complete",
    "Incomplete"
)

display(daily_completeness.head(10))

print("\nDaily completeness summary")
print("Dates checked:", len(daily_completeness))
print(
    "Dates with incomplete PROD:",
    (daily_completeness["PROD_Status"] == "Incomplete").sum()
)
print(
    "Dates with incomplete PKG:",
    (daily_completeness["PKG_Status"] == "Incomplete").sum()
)

  Report Date  Total_Lines  PROD_Missing  PKG_Missing PROD_Status  PKG_Status
0  2026-05-01            9             1            1  Incomplete  Incomplete
1  2026-05-02            9             1            1  Incomplete  Incomplete
2  2026-05-03            9             1            1  Incomplete  Incomplete
3  2026-05-04            9             1            1  Incomplete  Incomplete
4  2026-05-05            9             1            1  Incomplete  Incomplete
5  2026-05-06            9             1            1  Incomplete  Incomplete
6  2026-05-07            9             1            1  Incomplete  Incomplete
7  2026-05-08            9             1            1  Incomplete  Incomplete
8  2026-05-09            9             1            1  Incomplete  Incomplete
9  2026-05-10            9             1            1  Incomplete  Incomplete

Daily completeness summary
Dates checked: 30
Dates with incomplete PROD: 30
Dates with incomplete PKG: 30

In [25]:
# 27. EXPORT VALIDATION AND SUMMARY REPORTS
from pathlib import Path

report_file = Path("May_2026_Production_Summary_Reports.xlsx")

with pd.ExcelWriter(report_file, engine="openpyxl") as writer:
    validation_summary.to_excel(
        writer, sheet_name="Validation Summary", index=False
    )
    line_summary.to_excel(
        writer, sheet_name="Monthly Line Summary", index=False
    )
    completeness_report.to_excel(
        writer, sheet_name="Line Completeness", index=False
    )
    daily_completeness.to_excel(
        writer, sheet_name="Daily Completeness", index=False
    )
    daily_summary.to_excel(
        writer, sheet_name="Daily Summary", index=False
    )

print("Summary reports exported successfully.")
print("File:", report_file.resolve())
print("Sheets: 5")

Summary reports exported successfully.
File: D:\May_Analysis\notebooks\May_2026_Production_Summary_Reports.xlsx
Sheets: 5

In [26]:
# 28. FINAL FILE VERIFICATION
from pathlib import Path

files_to_check = [
    Path("May_2026_Validated_Master_Dataset.xlsx"),
    Path("May_2026_Production_Summary_Reports.xlsx")
]

for file in files_to_check:
    if file.exists():
        print(f"FOUND: {file.name}")
        print(f"Size: {file.stat().st_size / 1024:.2f} KB")
    else:
        print(f"NOT FOUND: {file.name}")

FOUND: May_2026_Validated_Master_Dataset.xlsx
Size: 18.01 KB
FOUND: May_2026_Production_Summary_Reports.xlsx
Size: 11.19 KB

In [27]:
# 29. DAILY PRODUCTION PERFORMANCE

daily_performance = (
    production_df.groupby("Report Date")
    .agg(
        Total_LCR=("LCR", "sum"),
        Total_PCR=("PCR", "sum"),
        Total_Wastage=("WASTAGE", "sum"),
        Available_PROD=("PROD", "sum"),
        Available_PKG=("PKG", "sum")
    )
    .reset_index()
)

# Calculate machine wastage percentage
daily_performance["Machine_Wastage_%"] = np.where(
    daily_performance["Total_LCR"] != 0,
    daily_performance["Total_Wastage"]
    / daily_performance["Total_LCR"] * 100,
    np.nan
)

# Mark production and packing totals as incomplete when values are missing
daily_performance["PROD_Complete"] = (
    production_df.groupby("Report Date")["PROD"]
    .apply(lambda s: s.notna().all())
    .to_numpy()
)

daily_performance["PKG_Complete"] = (
    production_df.groupby("Report Date")["PKG"]
    .apply(lambda s: s.notna().all())
    .to_numpy()
)

daily_performance.loc[
    ~daily_performance["PROD_Complete"], "Available_PROD"
] = np.nan

daily_performance.loc[
    ~daily_performance["PKG_Complete"], "Available_PKG"
] = np.nan

display(daily_performance.head(10))

print("\nDaily performance table created.")
print("Days analyzed:", len(daily_performance))

,Report Date,Total_LCR,Total_PCR,Total_Wastage,Available_PROD,Available_PKG,Machine_Wastage_%,PROD_Complete,PKG_Complete
0,2026-05-01,163163,160073,3090,NaN,NaN,1.893812,False,False
1,2026-05-02,159078,155721,3357,NaN,NaN,2.110286,False,False
2,2026-05-03,145955,143103,2852,NaN,NaN,1.954027,False,False
3,2026-05-04,164087,160941,3146,NaN,NaN,1.917276,False,False
4,2026-05-05,166686,163817,2869,NaN,NaN,1.721200,False,False
5,2026-05-06,162484,158846,3638,NaN,NaN,2.238990,False,False
6,2026-05-07,160230,157297,2933,NaN,NaN,1.830494,False,False
7,2026-05-08,164979,161035,3944,NaN,NaN,2.390607,False,False
8,2026-05-09,155628,152511,3117,NaN,NaN,2.002853,False,False
9,2026-05-10,165575,162076,3499,NaN,NaN,2.113242,False,False

Daily performance table created.
Days analyzed: 30

In [28]:
# 30. MONTHLY LINE-WISE PERFORMANCE

line_performance = (
    production_df.groupby("LINE")
    .agg(
        Days_Reported=("Report Date", "nunique"),
        Total_LCR=("LCR", "sum"),
        Total_PCR=("PCR", "sum"),
        Total_Machine_Wastage=("WASTAGE", "sum"),
        Available_PROD=("PROD", "sum"),
        Available_PKG=("PKG", "sum"),
        Missing_PROD=("PROD", lambda s: s.isna().sum()),
        Missing_PKG=("PKG", lambda s: s.isna().sum())
    )
    .reset_index()
)

# Calculate machine wastage percentage
line_performance["Machine_Wastage_%"] = np.where(
    line_performance["Total_LCR"] != 0,
    line_performance["Total_Machine_Wastage"]
    / line_performance["Total_LCR"] * 100,
    np.nan
)

# Do not present incomplete totals as complete totals
line_performance.loc[
    line_performance["Missing_PROD"] > 0, "Available_PROD"
] = np.nan

line_performance.loc[
    line_performance["Missing_PKG"] > 0, "Available_PKG"
] = np.nan

display(line_performance.round(2))

print("\nMonthly line-wise performance created.")

,LINE,Days_Reported,Total_LCR,Total_PCR,Total_Machine_Wastage,Available_PROD,Available_PKG,Missing_PROD,Missing_PKG,Machine_Wastage_%
0,1,30,533156,522789,10367,5759.0,518310.0,0,0,1.94
1,2,30,533207,521759,11448,5746.0,517140.0,0,0,2.15
2,3,30,530786,520460,10326,5733.0,515970.0,0,0,1.95
3,4,30,539655,529505,10150,5836.0,525240.0,0,0,1.88
4,5,30,547020,534082,12938,5882.0,529380.0,0,0,2.37
5,6,30,526801,517042,9759,5694.0,512460.0,0,0,1.85
6,7,30,542971,532296,10675,5867.0,528030.0,0,0,1.97
7,8,30,524937,514906,10031,5670.0,510300.0,0,0,1.91
8,9,30,548943,536386,12557,NaN,NaN,30,30,2.29

Monthly line-wise performance created.

In [29]:
# 31. HIGHLIGHT HIGHEST MACHINE WASTAGE

from IPython.display import display

# Find the maximum machine wastage
max_wastage = line_performance["Total_Machine_Wastage"].max()

# Highlight every row tied for the highest value
def highlight_max_wastage(row):
    if row["Total_Machine_Wastage"] == max_wastage:
        return [
            "background-color: yellow; color: black; font-weight: bold"
        ] * len(row)
    return [""] * len(row)

styled_line_performance = (
    line_performance.style
    .format(precision=2)
    .apply(highlight_max_wastage, axis=1)
)

display(styled_line_performance)

print("Highest total machine wastage:", max_wastage)
print(
    "Line(s) with highest machine wastage:",
    line_performance.loc[
        line_performance["Total_Machine_Wastage"] == max_wastage,
        "LINE"
    ].tolist()
)

Highest total machine wastage: 12938
Line(s) with highest machine wastage: [5]

In [30]:
# 32. HIGHLIGHT HIGHEST MACHINE WASTAGE PERCENTAGE

max_wastage_pct = line_performance["Machine_Wastage_%"].max()

def highlight_max_percentage(row):
    if row["Machine_Wastage_%"] == max_wastage_pct:
        return [
            "background-color: lightgreen; color: black; font-weight: bold"
        ] * len(row)
    return [""] * len(row)

display(
    line_performance.style
    .format(precision=2)
    .apply(highlight_max_percentage, axis=1)
)

print("Highest machine wastage percentage:", round(max_wastage_pct, 2), "%")
print(
    "Line(s) with highest wastage percentage:",
    line_performance.loc[
        line_performance["Machine_Wastage_%"] == max_wastage_pct,
        "LINE"
    ].tolist()
)

Highest machine wastage percentage: 2.37 %
Line(s) with highest wastage percentage: [5]

In [31]:
# 33. HIGHLIGHT HIGHEST DAILY MACHINE WASTAGE

max_daily_wastage = daily_performance["Total_Wastage"].max()

def highlight_max_daily_wastage(row):
    if row["Total_Wastage"] == max_daily_wastage:
        return [
            "background-color: yellow; color: black; font-weight: bold"
        ] * len(row)
    return [""] * len(row)

display(
    daily_performance.style
    .format(precision=2)
    .apply(highlight_max_daily_wastage, axis=1)
)

print("Highest daily machine wastage:", max_daily_wastage)

print("Date(s) with highest machine wastage:")
display(
    daily_performance.loc[
        daily_performance["Total_Wastage"] == max_daily_wastage,
        ["Report Date", "Total_Wastage", "Machine_Wastage_%"]
    ]
)

Highest daily machine wastage: 3985
Date(s) with highest machine wastage:

   Report Date  Total_Wastage  Machine_Wastage_%
25  2026-05-26           3985           2.543465

In [32]:
# 34. OPERATIONAL WASTAGE AND PERCENTAGE BY LINE

operational_df = production_df.copy()

# Calculate total wastage
operational_df["Total_Wastage"] = (
    operational_df["LCR"] - operational_df["PKG"]
)

# Calculate operational wastage
operational_df["Operational_Wastage"] = (
    operational_df["Total_Wastage"]
    - operational_df["WASTAGE"]
)

# Monthly summary by production line
operational_summary = (
    operational_df.groupby("LINE")
    .agg(
        Days_Reported=("Report Date", "nunique"),
        Total_PCR=("PCR", "sum"),
        Total_PKG=("PKG", "sum"),
        Total_Wastage=("Total_Wastage", "sum"),
        Machine_Wastage=("WASTAGE", "sum"),
        Operational_Wastage=("Operational_Wastage", "sum"),
        Missing_PKG=("PKG", lambda s: s.isna().sum())
    )
    .reset_index()
)

# Preserve unknown totals for lines with missing PKG
missing_pkg = operational_summary["Missing_PKG"] > 0

operational_summary.loc[
    missing_pkg,
    ["Total_PKG", "Total_Wastage", "Operational_Wastage"]
] = np.nan

# Operational wastage percentage relative to PCR
operational_summary["Operational_Wastage_%"] = np.where(
    operational_summary["Total_PCR"] > 0,
    operational_summary["Operational_Wastage"]
    / operational_summary["Total_PCR"] * 100,
    np.nan
)

# Identify highest values, excluding missing results
max_operational = operational_summary["Operational_Wastage"].max()
max_operational_pct = operational_summary["Operational_Wastage_%"].max()

# Highlight highest quantity in yellow and highest percentage in green
def highlight_operational(row):
    styles = [""] * len(row)

    if pd.notna(max_operational) and row["Operational_Wastage"] == max_operational:
        styles = [
            "background-color: yellow; color: black; font-weight: bold"
        ] * len(row)

    if (
        pd.notna(max_operational_pct)
        and row["Operational_Wastage_%"] == max_operational_pct
    ):
        styles = [
            "background-color: lightgreen; color: black; font-weight: bold"
        ] * len(row)

    return styles

display(
    operational_summary.style
    .format(precision=2, na_rep="N/A")
    .apply(highlight_operational, axis=1)
)

print("Highest operational wastage:", max_operational)
print(
    "Line(s):",
    operational_summary.loc[
        operational_summary["Operational_Wastage"] == max_operational,
        "LINE"
    ].tolist()
)

print("\nHighest operational wastage percentage:", round(max_operational_pct, 2), "%")
print(
    "Line(s):",
    operational_summary.loc[
        operational_summary["Operational_Wastage_%"] == max_operational_pct,
        "LINE"
    ].tolist()
)

Highest operational wastage: 4702.0
Line(s): [5]

Highest operational wastage percentage: 0.89 %
Line(s): [8]

In [34]:
# 35. DAILY OPERATIONAL WASTAGE 

# Use only records with available PKG
valid_operational_df = production_df.loc[
    production_df["PKG"].notna()
].copy()

# Operational wastage = Total wastage - Machine wastage
# Equivalent to PCR - PKG
valid_operational_df["Operational_Wastage"] = (
    (valid_operational_df["LCR"] - valid_operational_df["PKG"])
    - valid_operational_df["WASTAGE"]
)

# Daily summary for available records
daily_operational = (
    valid_operational_df.groupby("Report Date")
    .agg(
        Lines_With_PKG=("LINE", "nunique"),
        Total_PCR=("PCR", "sum"),
        Total_PKG=("PKG", "sum"),
        Operational_Wastage=("Operational_Wastage", "sum")
    )
    .reset_index()
)

# Operational wastage percentage relative to PCR
daily_operational["Operational_Wastage_%"] = np.where(
    daily_operational["Total_PCR"] > 0,
    daily_operational["Operational_Wastage"]
    / daily_operational["Total_PCR"] * 100,
    np.nan
)

# Highlight highest quantity and highest percentage
max_daily_operational = daily_operational["Operational_Wastage"].max()
max_daily_operational_pct = daily_operational["Operational_Wastage_%"].max()

def highlight_daily_operational(row):
    styles = [""] * len(row)

    if row["Operational_Wastage"] == max_daily_operational:
        styles = [
            "background-color: yellow; color: black; font-weight: bold"
        ] * len(row)

    if row["Operational_Wastage_%"] == max_daily_operational_pct:
        styles = [
            "background-color: lightgreen; color: black; font-weight: bold"
        ] * len(row)

    return styles

display(
    daily_operational.style
    .format(precision=2)
    .apply(highlight_daily_operational, axis=1)
)

print("Highest daily operational wastage:", max_daily_operational)
print(
    "Date(s):",
    daily_operational.loc[
        daily_operational["Operational_Wastage"] == max_daily_operational,
        "Report Date"
    ].dt.strftime("%d-%b-%Y").tolist()
)

print(
    "\nHighest daily operational wastage percentage:",
    round(max_daily_operational_pct, 2), "%"
)
print(
    "Date(s):",
    daily_operational.loc[
        daily_operational["Operational_Wastage_%"] == max_daily_operational_pct,
        "Report Date"
    ].dt.strftime("%d-%b-%Y").tolist()
)

Highest daily operational wastage: 1807.0
Date(s): ['11-May-2026']

Highest daily operational wastage percentage: 1.27 %
Date(s): ['11-May-2026']

In [35]:
# 37. MONTHLY PRODUCTION EFFICIENCY COMPARISON

efficiency = monthly_comparison.copy()

# 1. Packing efficiency: PKG relative to PROD
efficiency["PKG_vs_PROD_%"] = np.where(
    efficiency["Total_PROD"] > 0,
    efficiency["Total_PKG"] / efficiency["Total_PROD"] * 100,
    np.nan
)

# 2. Machine conversion: PCR relative to LCR
efficiency["PCR_vs_LCR_%"] = np.where(
    efficiency["Total_LCR"] > 0,
    efficiency["Total_PCR"] / efficiency["Total_LCR"] * 100,
    np.nan
)

# 3. Production per HMR unit
efficiency["PROD_per_HMR"] = np.where(
    efficiency["Total_HMR"] > 0,
    efficiency["Total_PROD"] / efficiency["Total_HMR"],
    np.nan
)

# 4. Packing relative to LCR
efficiency["PKG_vs_LCR_%"] = np.where(
    efficiency["Total_LCR"] > 0,
    efficiency["Total_PKG"] / efficiency["Total_LCR"] * 100,
    np.nan
)

efficiency_columns = [
    "LINE",
    "PKG_vs_PROD_%",
    "PCR_vs_LCR_%",
    "PROD_per_HMR",
    "PKG_vs_LCR_%"
]

efficiency_report = efficiency[efficiency_columns].copy()

display(efficiency_report.round(2))

NameError: name 'monthly_comparison' is not defined

In [36]:

# Recreate monthly line comparison

monthly_comparison = (
    production_df.groupby("LINE")
    .agg(
        Days_Reported=("Report Date", "nunique"),
        Total_HMR=("HMR", "sum"),
        Total_LCR=("LCR", "sum"),
        Total_PCR=("PCR", "sum"),
        Machine_Wastage=("WASTAGE", "sum"),
        Total_PROD=("PROD", "sum"),
        Total_PKG=("PKG", "sum"),
        Missing_PROD=("PROD", "count"),
        Missing_PKG=("PKG", "count")
    )
    .reset_index()
)

# Preserve missing totals when PROD or PKG is incomplete
monthly_comparison.loc[
    monthly_comparison["Missing_PROD"] < 30,
    "Total_PROD"
] = monthly_comparison.loc[
    monthly_comparison["Missing_PROD"] < 30,
    "Total_PROD"
]

monthly_comparison.loc[
    monthly_comparison["Missing_PROD"] == 0,
    "Total_PROD"
] = np.nan

monthly_comparison.loc[
    monthly_comparison["Missing_PKG"] == 0,
    "Total_PKG"
] = np.nan

print("Monthly comparison recreated.")
display(monthly_comparison)

Monthly comparison recreated.

,LINE,Days_Reported,Total_HMR,Total_LCR,Total_PCR,Machine_Wastage,Total_PROD,Total_PKG,Missing_PROD,Missing_PKG
0,1,30,536899,533156,522789,10367,5759.0,518310.0,30,30
1,2,30,544761,533207,521759,11448,5746.0,517140.0,30,30
2,3,30,540302,530786,520460,10326,5733.0,515970.0,30,30
3,4,30,549860,539655,529505,10150,5836.0,525240.0,30,30
4,5,30,554973,547020,534082,12938,5882.0,529380.0,30,30
5,6,30,534483,526801,517042,9759,5694.0,512460.0,30,30
6,7,30,553288,542971,532296,10675,5867.0,528030.0,30,30
7,8,30,532928,524937,514906,10031,5670.0,510300.0,30,30
8,9,30,553560,548943,536386,12557,NaN,NaN,0,0

In [37]:

# Calculate monthly production efficiency metrics

efficiency = monthly_comparison.copy()

efficiency["PKG_vs_PROD_%"] = (
    efficiency["Total_PKG"] / efficiency["Total_PROD"] * 100
)

efficiency["PCR_vs_LCR_%"] = (
    efficiency["Total_PCR"] / efficiency["Total_LCR"] * 100
)

efficiency["PROD_per_HMR"] = (
    efficiency["Total_PROD"] / efficiency["Total_HMR"]
)

efficiency["PKG_vs_LCR_%"] = (
    efficiency["Total_PKG"] / efficiency["Total_LCR"] * 100
)

efficiency_columns = [
    "LINE",
    "PKG_vs_PROD_%",
    "PCR_vs_LCR_%",
    "PROD_per_HMR",
    "PKG_vs_LCR_%"
]

efficiency_report = efficiency[efficiency_columns].copy()

display(efficiency_report.round(2))

   LINE  PKG_vs_PROD_%  PCR_vs_LCR_%  PROD_per_HMR  PKG_vs_LCR_%
0     1         9000.0         98.06          0.01         97.22
1     2         9000.0         97.85          0.01         96.99
2     3         9000.0         98.05          0.01         97.21
3     4         9000.0         98.12          0.01         97.33
4     5         9000.0         97.63          0.01         96.78
5     6         9000.0         98.15          0.01         97.28
6     7         9000.0         98.03          0.01         97.25
7     8         9000.0         98.09          0.01         97.21
8     9            NaN         97.71           NaN           NaN

In [38]:
# 38. HIGHLIGHT HIGHEST AND LOWEST EFFICIENCY BY LINE


from IPython.display import display

metric_columns = [
    "PKG_vs_PROD_%",
    "PCR_vs_LCR_%",
    "PROD_per_HMR",
    "PKG_vs_LCR_%"
]

def highlight_extremes(column):
    styles = pd.Series("", index=column.index)

    valid = column.dropna()

    if valid.empty:
        return styles

    # Highest value = green
    styles.loc[valid.index[valid == valid.max()]] = (
        "background-color: lightgreen; color: black; font-weight: bold"
    )

    # Lowest value = yellow
    styles.loc[valid.index[valid == valid.min()]] = (
        "background-color: yellow; color: black; font-weight: bold"
    )

    return styles

styled_efficiency = (
    efficiency_report.style
    .format(precision=2, na_rep="N/A")
    .apply(
        lambda col: highlight_extremes(col)
        if col.name in metric_columns
        else pd.Series("", index=col.index),
        axis=0
    )
)

display(styled_efficiency)

In [39]:
# 39. MONTHLY PRODUCTION PER HOUR BY LINE

production_per_hour = (
    production_df.groupby("LINE")
    .agg(
        Total_HMR=("HMR", "sum"),
        Total_PROD=("PROD", "sum"),
        Missing_PROD=("PROD", lambda s: s.isna().sum()),
        Days_Reported=("Report Date", "nunique")
    )
    .reset_index()
)

# Do not report a complete rate if production data is missing
production_per_hour.loc[
    production_per_hour["Missing_PROD"] > 0,
    "Total_PROD"
] = np.nan

production_per_hour["Production_Per_Hour"] = np.where(
    (production_per_hour["Total_HMR"] > 0)
    & production_per_hour["Total_PROD"].notna(),
    production_per_hour["Total_PROD"]
    / production_per_hour["Total_HMR"],
    np.nan
)

# Highlight the highest and lowest production rates
valid_rates = production_per_hour["Production_Per_Hour"].dropna()
highest_rate = valid_rates.max()
lowest_rate = valid_rates.min()

def highlight_production_rate(row):
    styles = [""] * len(row)
    rate = row["Production_Per_Hour"]

    if pd.notna(rate) and rate == highest_rate:
        styles = [
            "background-color: lightgreen; color: black; font-weight: bold"
        ] * len(row)
    elif pd.notna(rate) and rate == lowest_rate:
        styles = [
            "background-color: yellow; color: black; font-weight: bold"
        ] * len(row)

    return styles

display(
    production_per_hour.style
    .format(precision=2, na_rep="N/A")
    .apply(highlight_production_rate, axis=1)
)

print("Highest production per hour:", round(highest_rate, 2))
print(
    "Line(s):",
    production_per_hour.loc[
        production_per_hour["Production_Per_Hour"] == highest_rate,
        "LINE"
    ].tolist()
)

print("\nLowest production per hour:", round(lowest_rate, 2))
print(
    "Line(s):",
    production_per_hour.loc[
        production_per_hour["Production_Per_Hour"] == lowest_rate,
        "LINE"
    ].tolist()
)

Highest production per hour: 0.01
Line(s): [1]

Lowest production per hour: 0.01
Line(s): [2]

In [40]:
# EXPORT PRODUCTION METRICS TO AN EXCEL WORKBOOK

from pathlib import Path
import pandas as pd
import numpy as np

output_file = Path("May_2026_Production_Metrics.xlsx")

# Use existing analysis tables from your notebook
reports = {
    "Master Dataset": production_df,
    "Monthly Comparison": monthly_comparison,
    "Efficiency Comparison": efficiency_report,
    "Machine Wastage": line_performance,
    "Operational Wastage": operational_summary,
    "Production per Hour": production_per_hour,
    "Data Completeness": completeness_report,
    "Validation Summary": validation_summary,
}

# Keep only tables that currently exist in the notebook
available_reports = {
    name: table.copy()
    for name, table in reports.items()
    if name in globals() and isinstance(table, pd.DataFrame)
}

print("Reports available for export:")
for name, table in available_reports.items():
    print(f"{name}: {table.shape[0]} rows, {table.shape[1]} columns")

with pd.ExcelWriter(
    output_file,
    engine="openpyxl"
) as writer:
    for name, table in available_reports.items():
        # Excel worksheet names must be 31 characters or fewer
        table.to_excel(
            writer,
            sheet_name=name[:31],
            index=False
        )

print("\nExcel workbook exported:", output_file.resolve())
print("Worksheets created:", len(available_reports))

Reports available for export:

IndexError: At least one sheet must be visible

In [41]:
# FIXED: EXPORT PRODUCTION METRICS TO EXCEL
from pathlib import Path
import pandas as pd

output_file = Path("May_2026_Production_Metrics.xlsx")

reports = {
    "Master Dataset": "production_df",
    "Monthly Comparison": "monthly_comparison",
    "Efficiency Comparison": "efficiency_report",
    "Machine Wastage": "line_performance",
    "Operational Wastage": "operational_summary",
    "Production per Hour": "production_per_hour",
    "Data Completeness": "completeness_report",
    "Validation Summary": "validation_summary",
}

available_reports = {
    sheet_name: globals()[variable_name].copy()
    for sheet_name, variable_name in reports.items()
    if variable_name in globals()
    and isinstance(globals()[variable_name], pd.DataFrame)
}

if not available_reports:
    raise ValueError(
        "No analysis tables found. Check that the analysis cells have run."
    )

with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
    for sheet_name, table in available_reports.items():
        safe_name = sheet_name[:31]
        table.to_excel(writer, sheet_name=safe_name, index=False)

    # Ensure all exported sheets are visible
    for worksheet in writer.book.worksheets:
        worksheet.sheet_state = "visible"

print("Excel export completed successfully!")
print("File:", output_file.resolve())
print("Worksheets:", len(available_reports))

for sheet_name, table in available_reports.items():
    print(f"{sheet_name}: {len(table)} rows, {len(table.columns)} columns")

Excel export completed successfully!
File: D:\May_Analysis\notebooks\May_2026_Production_Metrics.xlsx
Worksheets: 8
Master Dataset: 270 rows, 9 columns
Monthly Comparison: 9 rows, 10 columns
Efficiency Comparison: 9 rows, 5 columns
Machine Wastage: 9 rows, 10 columns
Operational Wastage: 9 rows, 9 columns
Production per Hour: 9 rows, 6 columns
Data Completeness: 9 rows, 6 columns
Validation Summary: 13 rows, 3 columns

In [42]:
# STEP 2: PROFESSIONAL EXCEL FORMATTING
from openpyxl import load_workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.formatting.rule import ColorScaleRule
from openpyxl.utils import get_column_letter
from pathlib import Path

output_file = Path("May_2026_Production_Metrics.xlsx")
wb = load_workbook(output_file)

header_fill = PatternFill("solid", fgColor="1F4E78")
header_font = Font(color="FFFFFF", bold=True)
green_fill = PatternFill("solid", fgColor="C6EFCE")
yellow_fill = PatternFill("solid", fgColor="FFEB9C")
thin_gray = Side(style="thin", color="D9E2F3")

# Apply workbook formatting
for ws in wb.worksheets:
    ws.sheet_view.showGridLines = False
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions

    # Professional header formatting
    for cell in ws[1]:
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(
            horizontal="center",
            vertical="center",
            wrap_text=True
        )
        cell.border = Border(bottom=thin_gray)

    ws.row_dimensions[1].height = 30

    # Adjust column widths based on contents
    for col_idx in range(1, ws.max_column + 1):
        letter = get_column_letter(col_idx)
        values = [
            len(str(ws.cell(row, col_idx).value or ""))
            for row in range(1, min(ws.max_row, 200) + 1)
        ]
        width = min(max(max(values, default=10) + 2, 12), 32)
        ws.column_dimensions[letter].width = width

    # Highlight numeric metric columns using green-to-yellow scale
    for col_idx in range(1, ws.max_column + 1):
        header = str(ws.cell(1, col_idx).value or "").lower()

        if any(term in header for term in [
            "wastage", "efficiency", "per_hour",
            "vs_prod", "vs_lcr", "vs_pcr"
        ]):
            if ws.max_row >= 2:
                letter = get_column_letter(col_idx)
                ws.conditional_formatting.add(
                    f"{letter}2:{letter}{ws.max_row}",
                    ColorScaleRule(
                        start_type="min",
                        start_color="FFEB9C",
                        mid_type="percentile",
                        mid_value=50,
                        mid_color="FFFFFF",
                        end_type="max",
                        end_color="C6EFCE"
                    )
                )

    # Standard alignment for data cells
    for row in ws.iter_rows(min_row=2):
        for cell in row:
            cell.alignment = Alignment(vertical="center")

# Save formatted workbook
wb.save(output_file)

print("Professional formatting applied successfully.")
print("Workbook:", output_file.resolve())
print("Worksheets formatted:", len(wb.sheetnames))
print("Headers, filters, frozen panes, widths and metric color scales applied.")

Professional formatting applied successfully.
Workbook: D:\May_Analysis\notebooks\May_2026_Production_Metrics.xlsx
Worksheets formatted: 8
Headers, filters, frozen panes, widths and metric color scales applied.

In [43]:

from pathlib import Path
from openpyxl import load_workbook

file_path = Path("May_2026_Production_Metrics.xlsx")

if file_path.exists():
    wb_check = load_workbook(file_path, read_only=True)
    print("Workbook verified:", file_path.name)
    print("File size:", round(file_path.stat().st_size / 1024, 2), "KB")
    print("Worksheets:", wb_check.sheetnames)
    wb_check.close()
else:
    print("Workbook not found in the current directory.")

Workbook verified: May_2026_Production_Metrics.xlsx
File size: 27.4 KB
Worksheets: ['Master Dataset', 'Monthly Comparison', 'Efficiency Comparison', 'Machine Wastage', 'Operational Wastage', 'Production per Hour', 'Data Completeness', 'Validation Summary']

In [44]:
# STEP 3: PERFORMANCE-BASED HIGHLIGHTING

from openpyxl import load_workbook
from openpyxl.styles import PatternFill, Font
from pathlib import Path
import math

file_path = Path("May_2026_Production_Metrics.xlsx")
wb = load_workbook(file_path)

green_fill = PatternFill("solid", fgColor="C6EFCE")
red_fill = PatternFill("solid", fgColor="FFC7CE")

wastage_terms = ["wastage"]
efficiency_terms = [
    "production_per_hour",
    "prod_per_hmr",
    "pkg_vs_prod",
    "pcr_vs_lcr",
    "pkg_vs_lcr"
]

for ws in wb.worksheets:
    if ws.max_row < 3:
        continue

    for col_idx in range(1, ws.max_column + 1):
        header = str(ws.cell(1, col_idx).value or "").lower().replace(" ", "_")

        is_wastage = any(term in header for term in wastage_terms)
        is_efficiency = any(term in header for term in efficiency_terms)

        if not (is_wastage or is_efficiency):
            continue

        values = []
        for row_idx in range(2, ws.max_row + 1):
            value = ws.cell(row_idx, col_idx).value
            if isinstance(value, (int, float)) and not isinstance(value, bool):
                if math.isfinite(value):
                    values.append((row_idx, value))

        if not values:
            continue

        min_value = min(value for _, value in values)
        max_value = max(value for _, value in values)

        for row_idx, value in values:
            cell = ws.cell(row_idx, col_idx)

            if is_wastage:
                if value == min_value:
                    cell.fill = green_fill
                    cell.font = Font(color="006100", bold=True)
                if value == max_value:
                    cell.fill = red_fill
                    cell.font = Font(color="9C0006", bold=True)

            elif is_efficiency:
                if value == max_value:
                    cell.fill = green_fill
                    cell.font = Font(color="006100", bold=True)
                if value == min_value:
                    cell.fill = red_fill
                    cell.font = Font(color="9C0006", bold=True)

wb.save(file_path)

print("Performance-based highlighting completed.")
print("Updated workbook:", file_path.resolve())

Performance-based highlighting completed.
Updated workbook: D:\May_Analysis\notebooks\May_2026_Production_Metrics.xlsx

In [45]:
print("Final workbook:", file_path.resolve())
print("Exists:", file_path.exists())
print("Size (KB):", round(file_path.stat().st_size / 1024, 2))

Final workbook: D:\May_Analysis\notebooks\May_2026_Production_Metrics.xlsx
Exists: True
Size (KB): 27.49

In [46]:
# ADD TOTAL AND OPERATIONAL WASTAGE TO MASTER DATASET

master_dataset = production_df.copy()

# Total wastage: keep missing PKG values as missing
master_dataset["TOTAL_WAST"] = (
    master_dataset["LCR"] - master_dataset["PKG"]
)

# Operational wastage
master_dataset["OPERATIONAL_WASTAGE"] = (
    master_dataset["TOTAL_WAST"] - master_dataset["WASTAGE"]
)

# Operational wastage percentage relative to PCR
master_dataset["OPERATIONAL_WASTAGE_%"] = np.where(
    master_dataset["PCR"] > 0,
    master_dataset["OPERATIONAL_WASTAGE"]
    / master_dataset["PCR"] * 100,
    np.nan
)

# Display the updated dataset
display(master_dataset.head())

print("Rows:", len(master_dataset))
print("Columns:", len(master_dataset.columns))
print("New columns added:")
print([
    "TOTAL_WAST",
    "OPERATIONAL_WASTAGE",
    "OPERATIONAL_WASTAGE_%"
])

,Report Date,LINE,HMR,LCR,PCR,WASTAGE,% M/C,PROD,PKG,TOTAL_WAST,OPERATIONAL_WASTAGE,OPERATIONAL_WASTAGE_%
0,2026-05-01,1,16354,16528,16208,320,1.93611,178.0,16020.0,508.0,188.0,1.159921
1,2026-05-01,2,17634,17201,17113,88,0.51160,189.0,17010.0,191.0,103.0,0.601882
2,2026-05-01,3,17214,17103,16560,543,3.17488,182.0,16380.0,723.0,180.0,1.086957
3,2026-05-01,4,18681,19188,18997,191,0.99541,208.0,18720.0,468.0,277.0,1.458125
4,2026-05-01,5,18666,19053,18399,654,3.43253,202.0,18180.0,873.0,219.0,1.190282

Rows: 270
Columns: 12
New columns added:
['TOTAL_WAST', 'OPERATIONAL_WASTAGE', 'OPERATIONAL_WASTAGE_%']

In [47]:
# EXPORT UPDATED MASTER DATASET WITH REPORT DATA

from pathlib import Path
import pandas as pd
import numpy as np

master_dataset = production_df.copy()

# Ensure Report Date is retained and stored as datetime
master_dataset["Report Date"] = pd.to_datetime(
    master_dataset["Report Date"],
    errors="coerce"
)

# Total wastage = LCR - PKG
master_dataset["TOTAL_WAST"] = (
    master_dataset["LCR"] - master_dataset["PKG"]
)

# Operational wastage = Total wastage - machine wastage
master_dataset["OPERATIONAL_WASTAGE"] = (
    master_dataset["TOTAL_WAST"] - master_dataset["WASTAGE"]
)

# Operational wastage percentage relative to PCR
master_dataset["OPERATIONAL_WASTAGE_%"] = np.where(
    master_dataset["PCR"] > 0,
    master_dataset["OPERATIONAL_WASTAGE"]
    / master_dataset["PCR"] * 100,
    np.nan
)

# Set the required column order
columns = [
    "Report Date", "LINE", "HMR", "LCR", "PCR",
    "WASTAGE", "% M/C", "PROD", "PKG",
    "TOTAL_WAST", "OPERATIONAL_WASTAGE",
    "OPERATIONAL_WASTAGE_%"
]

master_dataset = master_dataset[columns]

# Export to Excel
master_file = Path("May_2026_Production_Master_Updated.xlsx")

master_dataset.to_excel(
    master_file,
    sheet_name="Master Dataset",
    index=False
)

print("Export successful!")
print("File:", master_file.resolve())
print("Rows:", len(master_dataset))
print("Columns:", len(master_dataset.columns))
print("Report Date retained:", "Report Date" in master_dataset.columns)

display(master_dataset.head())

Export successful!
File: D:\May_Analysis\notebooks\May_2026_Production_Master_Updated.xlsx
Rows: 270
Columns: 12
Report Date retained: True

,Report Date,LINE,HMR,LCR,PCR,WASTAGE,% M/C,PROD,PKG,TOTAL_WAST,OPERATIONAL_WASTAGE,OPERATIONAL_WASTAGE_%
0,2026-05-01,1,16354,16528,16208,320,1.93611,178.0,16020.0,508.0,188.0,1.159921
1,2026-05-01,2,17634,17201,17113,88,0.51160,189.0,17010.0,191.0,103.0,0.601882
2,2026-05-01,3,17214,17103,16560,543,3.17488,182.0,16380.0,723.0,180.0,1.086957
3,2026-05-01,4,18681,19188,18997,191,0.99541,208.0,18720.0,468.0,277.0,1.458125
4,2026-05-01,5,18666,19053,18399,654,3.43253,202.0,18180.0,873.0,219.0,1.190282